// Raw response from API (all values as strings)
export interface PlayerStatsResponse {
  "Entry Rate": string;
  "Headshots": string;
  "Utility Damage Success Rate": string;
  "Penta Kills": string;
  "Total Flash Count": string;
  "MVPs": string;
  "Flashes per Round": string;
  "Total Utility Successes": string;
  "1v2 Win Rate": string;
  "Utility Damage per Round": string;
  "Total Damage": string;
  "Total Entry Wins": string;
  "Average Deaths": string;
  "Total 1v1 Count": string;
  "Total Enemies Flashed": string;
  "1v1 Win Rate": string;
  "Average Quadro Kills": string;
  "Wins": number;
  "Entry Success Rate": string;
  "Total Headshots %": string;
  "Enemies Flashed per Round": string;
  "Total Sniper Kills": string;
  "Sniper Kill Rate": string;
  "Total Flash Successes": string;
  "Assists": string;
  "Average MVPs": string;
  "Average Penta Kills": string;
  "Utility Usage per Round": string;
  "Average Assists": string;
  "Average K/R Ratio": string;
  "Utility Success Rate": string;
  "Average K/D Ratio": string;
  "K/R Ratio": string;
  "Sniper Kill Rate per Round": string;
  "Kills": string;
  "Total 1v2 Count": string;
  "Total Kills with extended stats": string;
  "Triple Kills": string;
  "Total Entry Count": string;
  "Win Rate %": string;
  "Total Utility Count": string;
  "Flash Success Rate": string;
  "Total Matches": string;
  "Total Utility Damage": string;
  "Average Kills": string;
  "Average Headshots %": string;
  "K/D Ratio": string;
  "Matches": string;
  "Deaths": string;
  "Rounds": string;
  "Average Triple Kills": string;
  "Quadro Kills": string;
  "ADR": string;
  "Total 1v1 Wins": string;
  "Headshots per Match": string;
  "Total 1v2 Wins": string;
  "Total Rounds with extended stats": string;
}

// Formatted stats with proper types
export interface PlayerStats {
  "Entry Rate": number;
  "Headshots": number;
  "Utility Damage Success Rate": number;
  "Penta Kills": number;
  "Total Flash Count": number;
  "MVPs": number;
  "Flashes per Round": number;
  "Total Utility Successes": number;
  "1v2 Win Rate": number;
  "Utility Damage per Round": number;
  "Total Damage": number;
  "Total Entry Wins": number;
  "Average Deaths": number;
  "Total 1v1 Count": number;
  "Total Enemies Flashed": number;
  "1v1 Win Rate": number;
  "Average Quadro Kills": number;
  "Wins": number;
  "Entry Success Rate": number;
  "Total Headshots %": number;
  "Enemies Flashed per Round": number;
  "Total Sniper Kills": number;
  "Sniper Kill Rate": number;
  "Total Flash Successes": number;
  "Assists": number;
  "Average MVPs": number;
  "Average Penta Kills": number;
  "Utility Usage per Round": number;
  "Average Assists": number;
  "Average K/R Ratio": number;
  "Utility Success Rate": number;
  "Average K/D Ratio": number;
  "K/R Ratio": number;
  "Sniper Kill Rate per Round": number;
  "Kills": number;
  "Total 1v2 Count": number;
  "Total Kills with extended stats": number;
  "Triple Kills": number;
  "Total Entry Count": number;
  "Win Rate %": number;
  "Total Utility Count": number;
  "Flash Success Rate": number;
  "Total Matches": number;
  "Total Utility Damage": number;
  "Average Kills": number;
  "Average Headshots %": number;
  "K/D Ratio": number;
  "Matches": number;
  "Deaths": number;
  "Rounds": number;
  "Average Triple Kills": number;
  "Quadro Kills": number;
  "ADR": number;
  "Total 1v1 Wins": number;
  "Headshots per Match": number;
  "Total 1v2 Wins": number;
  "Total Rounds with extended stats": number;
  "Custom Combat Rating": number;
}
